"""
AquaGuard - Monitoring Report Model

Defines the MonitoringReport class used to combine water readings
and generate location-wise monitoring results.
"""

from dataclasses import dataclass
from statistics import mean

from models.location import LocationUser
from models.water_reading import WaterReading


@dataclass
class MonitoringReport:
    """
    Generates a monitoring report for one location.

    Attributes:
        location: The monitored LocationUser.
        readings: List of WaterReading objects belonging to the location.
    """

    location: LocationUser
    readings: list[WaterReading]

    @property
    def total_consumption(self) -> float:
        """Return total recorded water consumption."""

        return sum(reading.consumption_liters for reading in self.readings)

    @property
    def average_consumption(self) -> float:
        """Return average daily water consumption."""

        if not self.readings:
            return 0.0

        return mean(
            reading.consumption_liters
            for reading in self.readings
        )

    @property
    def quality_status(self) -> str:
        """Return the overall water-quality status."""

        if not self.readings:
            return "No Data"

        unsafe_count = sum(
            reading.quality_status == "Unsafe"
            for reading in self.readings
        )

        if unsafe_count > 0:
            return "Unsafe"

        return "Safe"

    @property
    def trend(self) -> str:
        """
        Determine the water-consumption trend.

        Returns:
            Increasing, Decreasing, Stable, or No Data.
        """

        if len(self.readings) < 2:
            return "No Data"

        ordered_readings = sorted(
            self.readings,
            key=lambda reading: reading.reading_date
        )

        values = [
            reading.consumption_liters
            for reading in ordered_readings
        ]

        first_average = mean(values[:max(1, len(values) // 2)])
        second_average = mean(values[-max(1, len(values) // 2):])

        difference = second_average - first_average

        if difference > 50:
            return "Increasing"

        if difference < -50:
            return "Decreasing"

        return "Stable"

    @property
    def alerts(self) -> list[str]:
        """Return all alerts generated by the location's readings."""

        alerts = []

        for reading in self.readings:
            alerts.extend(reading.alert_messages())

        return alerts

    @property
    def recommendations(self) -> list[str]:
        """Generate conservation and water-quality recommendations."""

        recommendations = []

        if not self.readings:
            return ["Add water readings to generate recommendations."]

        if self.average_consumption > self.location.target_daily_liters:
            recommendations.append(
                "Reduce unnecessary water consumption and check for leaks."
            )

        if self.trend == "Increasing":
            recommendations.append(
                "Water usage is increasing. Review recent consumption patterns."
            )

        if any(
            reading.turbidity_ntu > WaterReading.TURBIDITY_MAX
            for reading in self.readings
        ):
            recommendations.append(
                "Inspect the filtration system and retest water turbidity."
            )

        if any(
            reading.ph < WaterReading.PH_MIN
            or reading.ph > WaterReading.PH_MAX
            for reading in self.readings
        ):
            recommendations.append(
                "Inspect the water source and retest the pH value."
            )

        if not recommendations:
            recommendations.append(
                "Continue responsible water use and regular monitoring."
            )

        return recommendations

    @property
    def conservation_status(self) -> str:
        """Return a simple conservation performance status."""

        if not self.readings:
            return "No Data"

        if self.average_consumption <= self.location.target_daily_liters:
            return "Good"

        return "Needs Attention"

    def summary(self) -> dict:
        """Return the main report information as a dictionary."""

        return {
            "location": self.location.name,
            "type": self.location.location_type,
            "total_consumption": round(self.total_consumption, 2),
            "average_consumption": round(self.average_consumption, 2),
            "quality_status": self.quality_status,
            "consumption_trend": self.trend,
            "conservation_status": self.conservation_status,
            "alert_count": len(self.alerts),
            "recommendations": self.recommendations,
        }
