"""
AquaGuard - Beautiful Modern GUI
Using CustomTkinter (Best looking pure Python GUI library)
"""

import customtkinter as ctk
from datetime import date, datetime
from tkinter import messagebox
from typing import List, Dict

# Set modern dark theme
ctk.set_appearance_mode("Dark")
ctk.set_default_color_theme("blue")


# ==================== CLASSES (Same as before) ====================
class Location:
    def __init__(self, name: str, address: str, location_type: str = "Household"):
        self.name = name
        self.address = address
        self.location_type = location_type

    def __str__(self):
        return f"{self.name} ({self.location_type})"


class User:
    def __init__(self, user_id: str, name: str, role: str = "Resident"):
        self.user_id = user_id
        self.name = name
        self.role = role

    def __str__(self):
        return f"{self.name}"


class WaterReading:
    PH_MIN, PH_MAX = 6.5, 8.5
    TURBIDITY_LIMIT = 5.0
    CONSUMPTION_LIMIT = 450

    def __init__(self, reading_date, location, recorded_by, consumption, ph, turbidity):
        self.reading_date = reading_date
        self.location = location
        self.recorded_by = recorded_by
        self.consumption = consumption
        self.ph = ph
        self.turbidity = turbidity

    def is_abnormal(self):
        return (self.ph < self.PH_MIN or self.ph > self.PH_MAX or
                self.turbidity > self.TURBIDITY_LIMIT or
                self.consumption > self.CONSUMPTION_LIMIT)

    def get_alerts(self):
        alerts = []
        if self.ph < self.PH_MIN:
            alerts.append(f"Low pH ({self.ph})")
        elif self.ph > self.PH_MAX:
            alerts.append(f"High pH ({self.ph})")
        if self.turbidity > self.TURBIDITY_LIMIT:
            alerts.append(f"High turbidity ({self.turbidity} NTU)")
        if self.consumption > self.CONSUMPTION_LIMIT:
            alerts.append(f"High consumption ({self.consumption} L)")
        return alerts


class MonitoringReport:
    def __init__(self, report_id, generated_by, location):
        self.report_id = report_id
        self.generated_by = generated_by
        self.location = location
        self.readings = []
        self.generated_at = datetime.now()

    def add_reading(self, reading):
        self.readings.append(reading)

    def average_consumption(self):
        if not self.readings:
            return 0
        return sum(r.consumption for r in self.readings) / len(self.readings)

    def consumption_trend(self):
        if len(self.readings) < 2:
            return "Not enough data"
        sorted_r = sorted(self.readings, key=lambda x: x.reading_date)
        first, last = sorted_r[0].consumption, sorted_r[-1].consumption
        if last > first * 1.15:
            return "Increasing ⬆"
        elif last < first * 0.85:
            return "Decreasing ⬇"
        return "Stable →"

    def status(self):
        return "ATTENTION NEEDED ⚠" if any(r.is_abnormal() for r in self.readings) else "NORMAL ✓"

    def get_all_alerts(self):
        alerts = []
        for r in self.readings:
            for a in r.get_alerts():
                alerts.append(f"{r.reading_date}: {a}")
        return alerts

    def recommendations(self):
        recs = []
        if self.average_consumption() > 400:
            recs.append("Reduce daily water use. Check for leaks.")
        if "Increasing" in self.consumption_trend():
            recs.append("Usage is rising. Avoid unnecessary water use.")
        alerts = self.get_all_alerts()
        if any("turbidity" in a.lower() for a in alerts):
            recs.append("High turbidity → Use filtration or boil water.")
        if any("pH" in a for a in alerts):
            recs.append("pH out of range → Get water tested.")
        if not recs:
            recs.append("Everything is normal. Keep conserving water!")
        return recs

    def generate_text(self):
        lines = [
            "="*60,
            "          AQUAGUARD MONITORING REPORT",
            "="*60,
            f"Report ID      : {self.report_id}",
            f"Location       : {self.location}",
            f"Generated by   : {self.generated_by}",
            f"Generated on   : {self.generated_at.strftime('%d %b %Y, %I:%M %p')}",
            "-"*60,
            f"Status         : {self.status()}",
            f"Total Readings : {len(self.readings)}",
            f"Avg Consumption: {self.average_consumption():.1f} L/day",
            f"Trend          : {self.consumption_trend()}",
            "-"*60,
            "\nALERTS:"
        ]
        alerts = self.get_all_alerts()
        if alerts:
            lines.extend([f"  • {a}" for a in alerts])
        else:
            lines.append("  • No abnormal readings")

        lines.append("\nRECOMMENDATIONS:")
        lines.extend([f"  → {r}" for r in self.recommendations()])
        lines.append("\n" + "="*60)
        return "\n".join(lines)


# ==================== BEAUTIFUL GUI ====================
class AquaGuardApp(ctk.CTk):
    def __init__(self):
        super().__init__()

        self.title("AquaGuard • Water Quality & Usage Monitor")
        self.geometry("1100x720")
        self.minsize(1000, 650)

        # Data
        self.readings: List[WaterReading] = []
        self.load_sample_data()

        self.create_widgets()

    def load_sample_data(self):
        loc1 = Location("Green Villa", "Sector 12, Noida", "Household")
        loc2 = Location("Sunrise Apt", "Block B, Delhi", "Household")
        user1 = User("U101", "Priya Sharma")
        user2 = User("U102", "Rahul Verma")

        self.readings = [
            WaterReading(date(2026, 9, 8), loc1, user1, 310, 7.2, 2.1),
            WaterReading(date(2026, 9, 9), loc1, user1, 325, 7.0, 2.4),
            WaterReading(date(2026, 9, 10), loc1, user1, 480, 6.3, 3.0),
            WaterReading(date(2026, 9, 11), loc1, user1, 510, 7.1, 6.8),
            WaterReading(date(2026, 9, 9), loc2, user2, 290, 7.4, 1.8),
            WaterReading(date(2026, 9, 10), loc2, user2, 305, 7.3, 2.0),
            WaterReading(date(2026, 9, 11), loc2, user2, 298, 7.5, 1.9),
        ]

    def create_widgets(self):
        # ========== HEADER ==========
        header = ctk.CTkFrame(self, height=80, corner_radius=0, fg_color="#1a1a2e")
        header.pack(fill="x")
        header.pack_propagate(False)

        ctk.CTkLabel(header, text="💧  AquaGuard", font=ctk.CTkFont(size=28, weight="bold"),
                     text_color="#00d4ff").pack(side="left", padx=30, pady=20)

        ctk.CTkLabel(header, text="SDG 6 • Clean Water  |  SDG 12 • Responsible Consumption",
                     font=ctk.CTkFont(size=13), text_color="#aaaaaa").pack(side="left", pady=25)

        # ========== MAIN LAYOUT ==========
        main = ctk.CTkFrame(self, fg_color="transparent")
        main.pack(fill="both", expand=True, padx=20, pady=15)

        # Left Panel - Add Reading
        left = ctk.CTkFrame(main, width=340, corner_radius=15)
        left.pack(side="left", fill="y", padx=(0, 15))
        left.pack_propagate(False)

        ctk.CTkLabel(left, text="Add New Reading", font=ctk.CTkFont(size=18, weight="bold")).pack(pady=(20, 15))

        self.loc_entry = ctk.CTkEntry(left, placeholder_text="Location Name", height=38)
        self.loc_entry.pack(fill="x", padx=20, pady=6)

        self.addr_entry = ctk.CTkEntry(left, placeholder_text="Address", height=38)
        self.addr_entry.pack(fill="x", padx=20, pady=6)

        self.user_entry = ctk.CTkEntry(left, placeholder_text="User Name", height=38)
        self.user_entry.pack(fill="x", padx=20, pady=6)

        self.date_entry = ctk.CTkEntry(left, placeholder_text="Date (YYYY-MM-DD)", height=38)
        self.date_entry.pack(fill="x", padx=20, pady=6)
        self.date_entry.insert(0, str(date.today()))

        self.cons_entry = ctk.CTkEntry(left, placeholder_text="Consumption (Litres)", height=38)
        self.cons_entry.pack(fill="x", padx=20, pady=6)

        self.ph_entry = ctk.CTkEntry(left, placeholder_text="pH Value", height=38)
        self.ph_entry.pack(fill="x", padx=20, pady=6)

        self.turb_entry = ctk.CTkEntry(left, placeholder_text="Turbidity (NTU)", height=38)
        self.turb_entry.pack(fill="x", padx=20, pady=6)

        ctk.CTkButton(left, text="➕  Add Reading", height=42, font=ctk.CTkFont(size=15, weight="bold"),
                      command=self.add_reading, fg_color="#00b4d8", hover_color="#0096c7").pack(fill="x", padx=20, pady=20)

        ctk.CTkButton(left, text="📊  Generate Full Report", height=42, font=ctk.CTkFont(size=15, weight="bold"),
                      command=self.generate_report, fg_color="#0077b6", hover_color="#023e8a").pack(fill="x", padx=20, pady=(0, 10))

        ctk.CTkButton(left, text="🗑  Clear All", height=36, fg_color="#6c757d", hover_color="#495057",
                      command=self.clear_all).pack(fill="x", padx=20, pady=(0, 20))

        # Right Panel - Readings + Report
        right = ctk.CTkFrame(main, corner_radius=15)
        right.pack(side="right", fill="both", expand=True)

        ctk.CTkLabel(right, text="Recorded Readings", font=ctk.CTkFont(size=16, weight="bold")).pack(pady=(15, 8))

        self.reading_box = ctk.CTkTextbox(right, height=180, font=ctk.CTkFont(family="Consolas", size=13))
        self.reading_box.pack(fill="x", padx=15, pady=(0, 10))

        ctk.CTkLabel(right, text="Monitoring Report", font=ctk.CTkFont(size=16, weight="bold")).pack(pady=(5, 8))

        self.report_box = ctk.CTkTextbox(right, font=ctk.CTkFont(family="Consolas", size=13))
        self.report_box.pack(fill="both", expand=True, padx=15, pady=(0, 15))

        self.refresh_readings()

    def add_reading(self):
        try:
            loc_name = self.loc_entry.get().strip()
            address = self.addr_entry.get().strip()
            user_name = self.user_entry.get().strip()
            if not loc_name or not user_name:
                messagebox.showwarning("Missing", "Please fill Location and User name")
                return

            r_date = datetime.strptime(self.date_entry.get(), "%Y-%m-%d").date()
            cons = float(self.cons_entry.get())
            ph = float(self.ph_entry.get())
            turb = float(self.turb_entry.get())

            loc = Location(loc_name, address or "N/A")
            user = User("U" + str(len(self.readings)+1).zfill(3), user_name)
            reading = WaterReading(r_date, loc, user, cons, ph, turb)

            self.readings.append(reading)
            self.refresh_readings()

            # Clear inputs
            for e in [self.cons_entry, self.ph_entry, self.turb_entry]:
                e.delete(0, "end")

            messagebox.showinfo("Success", "Reading added successfully!")
        except Exception as e:
            messagebox.showerror("Error", "Please enter valid data\n(Date format: YYYY-MM-DD)")

    def refresh_readings(self):
        self.reading_box.delete("1.0", "end")
        if not self.readings:
            self.reading_box.insert("end", "No readings yet. Add some data!")
            return
        for r in sorted(self.readings, key=lambda x: x.reading_date):
            status = "⚠ ABNORMAL" if r.is_abnormal() else "✓ Normal"
            line = f"{r.reading_date} | {r.location.name:18} | {r.consumption:6.1f}L | pH {r.ph:4.1f} | Turb {r.turbidity:4.1f} | {status}\n"
            self.reading_box.insert("end", line)

    def generate_report(self):
        if not self.readings:
            messagebox.showwarning("No Data", "Please add at least one reading first")
            return

        # Group by location and show the first location's full report
        first = self.readings[0]
        report = MonitoringReport(
            f"AG-{datetime.now().strftime('%Y%m%d-%H%M')}",
            first.recorded_by,
            first.location
        )
        for r in self.readings:
            if r.location.name == first.location.name:
                report.add_reading(r)

        self.report_box.delete("1.0", "end")
        self.report_box.insert("end", report.generate_text())

    def clear_all(self):
        self.readings.clear()
        self.refresh_readings()
        self.report_box.delete("1.0", "end")
        messagebox.showinfo("Cleared", "All data cleared")


if __name__ == "__main__":
    app = AquaGuardApp()
    app.mainloop()
